import { Link } from "wouter";
import { motion } from "framer-motion";
import { ArrowRight, Shield, Lock, AlertTriangle, Activity } from "lucide-react";
import { NeonButton } from "@/components/NeonButton";
import { GlassCard } from "@/components/GlassCard";

const FEATURES = [
  {
    title: "Vulnerability Scanner",
    description: "Analyze passwords, detect misconfigurations, and simulate basic attacks.",
    icon: ScanSearch,
    color: "primary",
    href: "/scanner"
  },
  {
    title: "Breach Detection",
    description: "Check if your email or domains appear in known data leaks.",
    icon: AlertTriangle,
    color: "destructive",
    href: "/breach-checker"
  },
  {
    title: "Threat Simulation",
    description: "Interactive visual walkthroughs of common cyber attack vectors.",
    icon: Activity,
    color: "accent",
    href: "/attack-simulation"
  },
  {
    title: "Security Posture",
    description: "Your personalized dashboard tracking local scan history and risks.",
    icon: Shield,
    color: "success",
    href: "/dashboard"
  }
];

// Need to import ScanSearch manually here since it wasn't in the upper import list
import { ScanSearch } from "lucide-react";

export default function Home() {
  return (
    <div className="flex flex-col items-center">
      {/* Hero Section */}
      <section className="w-full py-20 lg:py-32 flex flex-col items-center text-center relative">
        {/* Background Image generated by AI */}
        <div className="absolute inset-0 z-[-1] opacity-20 mask-image:linear-gradient(to_bottom,black,transparent)">
          <img 
            src={`${import.meta.env.BASE_URL}images/cyber-bg.png`} 
            alt="Cyber Background" 
            className="w-full h-full object-cover"
          />
        </div>

        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="mb-6 relative"
        >
          <div className="absolute inset-0 blur-3xl bg-primary/30 rounded-full w-32 h-32 mx-auto"></div>
          <img 
            src={`${import.meta.env.BASE_URL}images/shield-logo.png`} 
            alt="RiskRadar Logo" 
            className="w-32 h-32 mx-auto relative z-10 drop-shadow-[0_0_15px_rgba(0,240,255,0.8)]"
          />
        </motion.div>

        <motion.h1 
          className="text-5xl md:text-7xl font-bold mb-6 max-w-4xl text-glow-primary leading-tight"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          See Your Security Risks <br/>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-accent to-primary">
            Before Hackers Do
          </span>
        </motion.h1>
        
        <motion.p 
          className="text-xl text-muted-foreground mb-10 max-w-2xl"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
        >
          A client-side intelligence platform to analyze vulnerabilities, check for breaches, and improve your digital defense posture without sending your data to the cloud.
        </motion.p>

        <motion.div 
          className="flex flex-col sm:flex-row gap-4"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.6 }}
        >
          <Link href="/scanner">
            <NeonButton size="lg" icon={<ScanSearch className="w-5 h-5" />}>
              Run Security Scan
            </NeonButton>
          </Link>
          <Link href="/dashboard">
            <NeonButton variant="outline" size="lg" icon={<LayoutDashboard className="w-5 h-5" />}>
              View Dashboard
            </NeonButton>
          </Link>
        </motion.div>
      </section>

      {/* Features Grid */}
      <section className="w-full py-16">
        <div className="flex items-center gap-4 mb-12">
          <div className="h-px bg-white/10 flex-1"></div>
          <h2 className="text-2xl font-display text-muted-foreground uppercase tracking-widest">Core Capabilities</h2>
          <div className="h-px bg-white/10 flex-1"></div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {FEATURES.map((feature, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.8 + (i * 0.1) }}
            >
              <Link href={feature.href} className="block h-full">
                <GlassCard hoverEffect glowColor={feature.color as any} className="h-full group cursor-pointer">
                  <div className={`w-12 h-12 rounded-lg bg-${feature.color}/10 border border-${feature.color}/30 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
                    <feature.icon className={`w-6 h-6 text-${feature.color}`} />
                  </div>
                  <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
                  <p className="text-muted-foreground text-sm">{feature.description}</p>
                </GlassCard>
              </Link>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  );
}

// Need to import Dashboard icon manually here since it wasn't in the upper import list
import { LayoutDashboard } from "lucide-react";
